server:
  port: 8083

spring:
  datasource:
    url: jdbc:sqlite:${SQLITE_DB_PATH:order-service.db}
    driver-class-name: org.sqlite.JDBC

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
    show-sql: false

jwt:
  secret: ${JWT_SECRET}

services:
  product-service:
    url: ${PRODUCT_SERVICE_URL:http://product-service:8082}
