server:
  port: 8081

spring:
  datasource:
    url: jdbc:sqlite:${SQLITE_DB_PATH:auth-service.db}
    driver-class-name: org.sqlite.JDBC

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
    show-sql: false

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
