server:
  port: 8082

spring:
  datasource:
    url: jdbc:sqlite:${SQLITE_DB_PATH:product-service.db}
    driver-class-name: org.sqlite.JDBC

  sql:
    init:
      mode: always
      continue-on-error: false

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
    show-sql: false
