server:
  port: 8082

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: noker
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
